export const NEWS_API = 'NEWS_API';
export const NEWS_API_SUCCESS = 'NEWS_API_SUCCESS';
export const NEWS_API_FAILED = 'NEWS_API_FAILED';

export const NEWS_DETAIL_API = 'NEWS_DETAIL_API';
export const NEWS_DETAIL_API_SUCCESS = 'NEWS_DETAIL_API_SUCCESS';
export const NEWS_DETAIL_API_FAILED = 'NEWS_DETAIL_API_FAILED';
export const RESET_NEWS_DETAIL = 'RESET_NEWS_DETAIL';
